> Changed hiding/showing actionbar from onSingleTapUp to onSingleTapConfirm so that double tap on image will not zoom and hide the action bar at the same time.
> Researching on download manager. Security issue is happening
 Error: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.alcodes.alcodessmgalleryviewer/external_files/Android/data/com.alcodes.alcodesgalleryviewerdemo/files/application/pdf/iso_8859-1.txt from pid=11271, uid=1000 requires the provider be exported, or grantUriPermission()

  - Had tried to change the android:exported = true, but it dint work (directly crashed).
  - Assuming android 10 and 11 no longer allow access from file with uri contains "file://"
  - Found out that download manager does not support Uri with scheme "content://" but support Uri with scheme "file://"

 However, android 7 works perfectly.